### ISSUE TITLE
Iris Normalization help 

### ISSUE THREAD

**Issue by hitmank** [mike10004/easyeye#1]
hey mike,
                  I am writing c# code for iris recognition on Emgucv, i have segmented the iris using hough circles (though not very accurately), and now i need to normalize the circular strip into a rectangular one.
I saw Masek's matlab code and now i am trying to convert it c#. I will use your c code as reference, however i would like to contact you by email in case i have some difficulties. (if not email ,any other method of your choice).
i am slightly new to serious programming and would really appreciate some help.
I promise not to bombard you with messages. I will ask for help only if needed. Please do reply / send me a mail at  karan_b77@hotmail.com if you are willing to help me out.

**Comment by mike10004** [comment]
Glad to help. If you're comfortable asking questions on this issue thread, then let's do that so that other people can benefit from what's said. Otherwise I'll send you an email.

**Comment by hitmank** [comment]
yes mike, discussing here is fine.
I have made some progress on my project . Its a little late now, so i will update you tomorrow.
And thanks for the response :)

**Comment by hitmank** [comment]
Hello Mike!
Well, right now i am just about done with my segmentation and normalization phases of the project.So, the focus is now on Feature extraction, and this is where i really feel out of my depth. I have tried reading as much theory as possible on the subject and i am still not really sure what I am supposed to do here. 
    My basic understanding is that I have to convert my normalized image into a template ( a binary code?). After reading up on this, I have understood that i have to apply a filter to my image and once my image passes through this filter i will be left with my template. My first question to you is , Have i got this bit right?
   Now, assuming that I have, Gabor filters seem to be the most commonly used here.I wish to start with them ( or anything else you suggest) . Please do tell me how to go about it from here.

**Comment by mike10004** [comment]
You've got the right idea. I would take a look at the <code>EncodeIris</code> function in [easyeye_encode.cc](https://github.com/mike10004/easyeye/blob/master/easyeye/src/easyeye/encode/easyeye_encode.cc), which calls the <code>encode</code> function in [optimasek/src/encode.cpp](https://github.com/mike10004/easyeye/blob/master/optimasek/src/encode.cpp), which uses Gabor filter code in [optimasek/src/gaborconvolve.cpp](https://github.com/mike10004/easyeye/blob/master/optimasek/src/gaborconvolve.cpp).
